const FETCH_PROMOTIONS = 'FETCH_PROMOTIONS';
const FETCH_PROMOTION = 'FETCH_PROMOTION';
const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';

export {
  FETCH_PROMOTIONS,
  FETCH_PROMOTION,
  FETCH_CURRENT_USER,
  LOGIN,
  LOGOUT,
};
