const GET_PROMOTIONS_LIST = 'GET_PROMOTIONS_LIST';
const GET_PROMOTIONS_LOADING = 'GET_PROMOTIONS_LOADING';
const GET_PROMOTIONS_ERROR = 'GET_PROMOTIONS_ERROR';

export {
  GET_PROMOTIONS_LIST,
  GET_PROMOTIONS_LOADING,
  GET_PROMOTIONS_ERROR,
};
