const GET_PROMOTIONS_LIST = 'GET_PROMOTIONS_LIST';
const GET_PROMOTIONS_LOADING = 'GET_PROMOTIONS_LOADING';
const GET_PROMOTIONS_ERROR = 'GET_PROMOTIONS_ERROR';
const GET_PROMOTION_DATA = 'GET_PROMOTION_DATA';
const GET_PROMOTION_LOADING = 'GET_PROMOTION_LOADING';
const GET_PROMOTION_ERROR = 'GET_PROMOTION_ERROR';
const GET_CURRENT_USER = 'SET_CURRENT_USER';
const GET_CURRENT_USER_LOADING = 'SET_CURRENT_USER_LOADING';

export {
  GET_PROMOTIONS_LIST,
  GET_PROMOTIONS_LOADING,
  GET_PROMOTIONS_ERROR,
  GET_PROMOTION_DATA,
  GET_PROMOTION_LOADING,
  GET_PROMOTION_ERROR,
  GET_CURRENT_USER,
  GET_CURRENT_USER_LOADING,
};
