const GET_PROMOTIONS_LIST = 'GET_PROMOTIONS_LIST';
const GET_PROMOTIONS_LOADING = 'GET_PROMOTIONS_LOADING';
const GET_PROMOTIONS_ERROR = 'GET_PROMOTIONS_ERROR';
const GET_PROMOTION_DATA = 'GET_PROMOTION_DATA';
const GET_PROMOTION_LOADING = 'GET_PROMOTION_LOADING';
const GET_PROMOTION_ERROR = 'GET_PROMOTION_ERROR';

export {
  GET_PROMOTIONS_LIST,
  GET_PROMOTIONS_LOADING,
  GET_PROMOTIONS_ERROR,
  GET_PROMOTION_DATA,
  GET_PROMOTION_LOADING,
  GET_PROMOTION_ERROR,
};
