const SET_PROMOTIONS_LIST = 'SET_PROMOTIONS_LIST';
const SET_PROMOTIONS_LOADING = 'SET_PROMOTIONS_LOADING';
const SET_PROMOTIONS_ERROR = 'SET_PROMOTIONS_ERROR';
const SET_PROMOTION_DATA = 'SET_PROMOTION_DATA';
const SET_PROMOTION_LOADING = 'SET_PROMOTION_LOADING';
const SET_PROMOTION_ERROR = 'SET_PROMOTION_ERROR';

export {
  SET_PROMOTIONS_LIST,
  SET_PROMOTIONS_LOADING,
  SET_PROMOTIONS_ERROR,
  SET_PROMOTION_DATA,
  SET_PROMOTION_LOADING,
  SET_PROMOTION_ERROR,
};
