const SET_PROMOTIONS_LIST = 'SET_PROMOTIONS_LIST';
const SET_PROMOTIONS_LOADING = 'SET_PROMOTIONS_LOADING';
const SET_PROMOTIONS_ERROR = 'SET_PROMOTIONS_ERROR';

export {
  SET_PROMOTIONS_LIST,
  SET_PROMOTIONS_LOADING,
  SET_PROMOTIONS_ERROR,
};
